package com.paymentservice.backend.payments;

import static com.paymentservice.backend.payments.PaymentModels.PaymentCreatedResponse;
import static com.paymentservice.backend.payments.PaymentModels.PaymentDetailsResponse;
import static com.paymentservice.backend.payments.PaymentModels.PaymentMethodOption;
import static com.paymentservice.backend.payments.PaymentModels.PaymentMethodType;
import static com.paymentservice.backend.payments.PaymentModels.PaymentRequest;
import static com.paymentservice.backend.payments.PaymentModels.PaymentStatus;
import static com.paymentservice.backend.payments.PaymentModels.ReceiptLineItem;
import static com.paymentservice.backend.payments.PaymentModels.ReceiptResponse;
import static com.paymentservice.backend.payments.PaymentModels.SimulationMode;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

@Service
public class PaymentService {

	private static final String MERCHANT_NAME = "Nova Payments";
	private static final String SUPPORT_CONTACT = "support@novapayments.example";

	private final Map<String, PaymentTransaction> transactions = new ConcurrentHashMap<>();

	public List<PaymentMethodOption> getPaymentMethods() {
		return List.of(
			new PaymentMethodOption(
				PaymentMethodType.UPI,
				"UPI",
				"Fast bank account payments",
				"Collect a UPI ID and confirm the payment with a lightweight flow.",
				"#38bdf8"
			),
			new PaymentMethodOption(
				PaymentMethodType.CREDIT_CARD,
				"Credit Card",
				"Visa, Mastercard, Rupay",
				"Capture card credentials and route them through the backend orchestration API.",
				"#8b5cf6"
			),
			new PaymentMethodOption(
				PaymentMethodType.DEBIT_CARD,
				"Debit Card",
				"Bank-linked card payments",
				"Model debit card checkout, authorization, and error handling screens.",
				"#22c55e"
			),
			new PaymentMethodOption(
				PaymentMethodType.UPI_QR,
				"UPI QR",
				"Scan-and-pay experience",
				"Present a QR-style UI and track the resulting payment in the same transaction flow.",
				"#f97316"
			)
		);
	}

	public PaymentCreatedResponse createPayment(PaymentRequest request) {
		validateMethodSpecificFields(request);

		OffsetDateTime now = OffsetDateTime.now(ZoneOffset.UTC);
		String paymentId = UUID.randomUUID().toString();
		PaymentStatus finalStatus = request.simulationMode() == SimulationMode.FAILED
			? PaymentStatus.FAILED
			: PaymentStatus.SUCCESS;

		PaymentTransaction transaction = new PaymentTransaction(
			paymentId,
			request.orderId().trim(),
			request.amount().setScale(2, RoundingMode.HALF_UP),
			request.currency().trim().toUpperCase(),
			request.paymentMethod(),
			PaymentStatus.PROCESSING,
			finalStatus,
			MERCHANT_NAME,
			maskedInstrument(request),
			request.customerName().trim(),
			request.customerEmail().trim().toLowerCase(),
			referenceNumber(),
			qrPayload(request),
			finalStatus == PaymentStatus.FAILED
				? "The issuing bank declined the payment in this demo flow."
				: null,
			receiptNumber(),
			now,
			now
		);

		transactions.put(paymentId, transaction);

		return new PaymentCreatedResponse(
			transaction.paymentId,
			transaction.status,
			"Payment initiated successfully. Poll the transaction endpoint for a final outcome.",
			1500,
			transaction.createdAt
		);
	}

	public PaymentDetailsResponse getPayment(String paymentId) {
		PaymentTransaction transaction = getRequiredTransaction(paymentId);
		advanceStatus(transaction);
		return toDetailsResponse(transaction);
	}

	public ReceiptResponse getReceipt(String paymentId) {
		PaymentTransaction transaction = getRequiredTransaction(paymentId);
		advanceStatus(transaction);

		return new ReceiptResponse(
			transaction.paymentId,
			transaction.receiptNumber,
			transaction.merchantName,
			transaction.amount,
			transaction.currency,
			transaction.paymentMethod,
			transaction.status,
			transaction.customerName,
			transaction.customerEmail,
			transaction.referenceNumber,
			List.of(
				new ReceiptLineItem("Checkout amount", transaction.amount),
				new ReceiptLineItem("Gateway fee", BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP))
			),
			SUPPORT_CONTACT,
			"Demo receipt generated by the Spring Boot backend service.",
			transaction.updatedAt
		);
	}

	private void validateMethodSpecificFields(PaymentRequest request) {
		switch (request.paymentMethod()) {
			case UPI -> {
				if (isBlank(request.upiId())) {
					throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "UPI ID is required for UPI payments.");
				}
			}
			case CREDIT_CARD, DEBIT_CARD -> {
				if (isBlank(request.cardHolderName())
					|| isBlank(request.cardNumber())
					|| isBlank(request.expiryMonth())
					|| isBlank(request.expiryYear())
					|| isBlank(request.cvv())) {
					throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Complete card details are required for card payments.");
				}
			}
			case UPI_QR -> {
				if (isBlank(request.qrReference())) {
					throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "QR reference is required for UPI QR payments.");
				}
			}
		}
	}

	private PaymentTransaction getRequiredTransaction(String paymentId) {
		PaymentTransaction transaction = transactions.get(paymentId);
		if (transaction == null) {
			throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Payment with ID '" + paymentId + "' was not found.");
		}
		return transaction;
	}

	private void advanceStatus(PaymentTransaction transaction) {
		if (transaction.status != PaymentStatus.PROCESSING) {
			return;
		}

		transaction.statusChecks += 1;
		if (transaction.statusChecks >= 2) {
			transaction.status = transaction.finalStatus;
			transaction.updatedAt = OffsetDateTime.now(ZoneOffset.UTC);
		}
	}

	private PaymentDetailsResponse toDetailsResponse(PaymentTransaction transaction) {
		return new PaymentDetailsResponse(
			transaction.paymentId,
			transaction.orderId,
			transaction.amount,
			transaction.currency,
			transaction.paymentMethod,
			transaction.status,
			transaction.merchantName,
			transaction.maskedInstrument,
			transaction.customerName,
			transaction.customerEmail,
			transaction.referenceNumber,
			transaction.qrPayload,
			transaction.status == PaymentStatus.FAILED ? transaction.failureReason : null,
			transaction.createdAt,
			transaction.updatedAt
		);
	}

	private String maskedInstrument(PaymentRequest request) {
		return switch (request.paymentMethod()) {
			case UPI -> "UPI ID: " + request.upiId().trim();
			case CREDIT_CARD -> "Credit Card •••• " + lastFourDigits(request.cardNumber());
			case DEBIT_CARD -> "Debit Card •••• " + lastFourDigits(request.cardNumber());
			case UPI_QR -> "QR Reference: " + request.qrReference().trim();
		};
	}

	private String qrPayload(PaymentRequest request) {
		if (request.paymentMethod() != PaymentMethodType.UPI_QR) {
			return null;
		}

		return "upi://pay?pa=merchant@upi&pn=Nova%20Payments&am="
			+ request.amount().setScale(2, RoundingMode.HALF_UP)
			+ "&tn="
			+ request.qrReference().trim();
	}

	private String lastFourDigits(String cardNumber) {
		String digits = cardNumber.replaceAll("\\s+", "");
		return digits.substring(Math.max(0, digits.length() - 4));
	}

	private String referenceNumber() {
		return "TXN-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase();
	}

	private String receiptNumber() {
		return "RCP-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase();
	}

	private boolean isBlank(String value) {
		return value == null || value.isBlank();
	}

	private static final class PaymentTransaction {

		private final String paymentId;
		private final String orderId;
		private final BigDecimal amount;
		private final String currency;
		private final PaymentMethodType paymentMethod;
		private final PaymentStatus finalStatus;
		private final String merchantName;
		private final String maskedInstrument;
		private final String customerName;
		private final String customerEmail;
		private final String referenceNumber;
		private final String qrPayload;
		private final String failureReason;
		private final String receiptNumber;
		private final OffsetDateTime createdAt;

		private PaymentStatus status;
		private OffsetDateTime updatedAt;
		private int statusChecks;

		private PaymentTransaction(
			String paymentId,
			String orderId,
			BigDecimal amount,
			String currency,
			PaymentMethodType paymentMethod,
			PaymentStatus status,
			PaymentStatus finalStatus,
			String merchantName,
			String maskedInstrument,
			String customerName,
			String customerEmail,
			String referenceNumber,
			String qrPayload,
			String failureReason,
			String receiptNumber,
			OffsetDateTime createdAt,
			OffsetDateTime updatedAt
		) {
			this.paymentId = paymentId;
			this.orderId = orderId;
			this.amount = amount;
			this.currency = currency;
			this.paymentMethod = paymentMethod;
			this.status = status;
			this.finalStatus = finalStatus;
			this.merchantName = merchantName;
			this.maskedInstrument = maskedInstrument;
			this.customerName = customerName;
			this.customerEmail = customerEmail;
			this.referenceNumber = referenceNumber;
			this.qrPayload = qrPayload;
			this.failureReason = failureReason;
			this.receiptNumber = receiptNumber;
			this.createdAt = createdAt;
			this.updatedAt = updatedAt;
			this.statusChecks = 0;
		}
	}
}
